### ISSUE TITLE
MEMSQL Functionality

### ISSUE THREAD

**Issue by mcarol44** [albertodonato/query-exporter#102]
Can we use query exporter for MEMSQL or do you know which exporter I can use for MEMSQL integration into prometheus.

**Comment by albertodonato** [comment]
Sorry I have no experience with MemSQL.

Note that query-exporter uses SQLAchelmy, so any supported database driver should work, you should just need to install it and use the right `dialect+driver//` in the DSN.

Looking at [this link](https://docs.singlestore.com/managed-service/en/developer-resources/connect-with-application-development-tools/connect-with-python/connect-with-sqlalchemy.html) it seems you could just use the `mysql` driver?
