### ISSUE TITLE
impala support

### ISSUE THREAD

**Issue by PaulYuanJ** [albertodonato/query-exporter#103]
Hey, @albertodonato

query exporter is a good solution to monitor database, i like it very much.

As I know superset use sqlalchemy to connect different databases, query exporter use it as well, if we can have a version to support connecting impala, it will be perfect~

**Comment by albertodonato** [comment]
Hi, I don't have experience with impala, but AFAICS [impyla](https://github.com/cloudera/impyla) has a SQLAlchemy driver for it.

So it should be enough to install it among dependencies to be able to use it with the `impala://` schema.
