### ISSUE TITLE
column name problem

### ISSUE THREAD

**Issue by TipTopBY** [albertodonato/query-exporter#104]
Hello, help a newbie with a problem.
I have the following configuration:

```
databases:
  db-ora-alseda02:
    dsn: oracle://MONITORING:MONITORING@X.X.X.X/AWX

metrics:
  COUNT:
    type: gauge
    description: Number of sessions


queries:
  alseda_stats:
    databases: [db-ora-alseda02]
    metrics: [COUNT]
    sql: >
      select count(*) as COUNT
      from mobilebanking.AUTH_JOURNAL aj,
      mobilebanking.statistic_journal sj
      where aj.operation_id=sj.OPERATION_ID
      and sj.DTYPE='authentication'
      and aj.PLATFORM in ('IOS','ANDROID')
      and sj.OPERATION_TIME > sysdate - 1/60/24
```
with which I am getting the error:

INFO - aiohttp.web - Listening on http://0.0.0.0:9560
INFO - query-exporter - version 2.8.0 starting up    
DEBUG - query-exporter - connected to database "db-ora-alseda02"
DEBUG - query-exporter - running query "alseda_stats" on database "db-ora-alseda02"
ERROR - query-exporter - query "alseda_stats" on database "db-ora-alseda02" failed: Wrong column names from query
DEBUG - query-exporter -   File "/virtualenv/lib/python3.8/site-packages/query_exporter/db.py", line 317, in execute
    return query.results(await QueryResults.from_results(result))
  File "/virtualenv/lib/python3.8/site-packages/query_exporter/db.py", line 210, in results
    raise InvalidResultColumnNames()
DEBUG - query-exporter - updating metric "queries" inc 1 {database="db-ora-alseda02",query="alseda_stats",status="error"}
DEBUG - query-exporter - removing doomed query "alseda_stats" for database "db-ora-alseda02"

At the same time, the same query through the SQL client gives me:

_________________
| ______|  CPUNT|
|  ____1| _____ 0  |
__________________

Which is the correct value. 

Where am I making a mistake?

**Comment by albertodonato** [comment]
Can you try using a different name than `COUNT` for the metric and the column alias?

**Comment by TipTopBY** [comment]
metrics:
  Users:
    type: gauge
    description: Number of sessions


queries:
  alseda_stats:
    databases: [db-ora-alseda02]
    metrics: [Users]
    sql: >
      select count(*) as Users
      from mobilebanking.AUTH_JOURNAL aj,
      mobilebanking.statistic_journal sj
      where aj.operation_id=sj.OPERATION_ID
      and sj.DTYPE='authentication'
      and aj.PLATFORM in ('IOS','ANDROID')
      and sj.OPERATION_TIME > sysdate - 1/60/24

Same error with this config.

**Comment by albertodonato** [comment]
Try using all-lowercase identifiers (e.g. `users` instead of `Users`.

**Comment by TipTopBY** [comment]
Yes, it worked. I am very grateful to you. It might be worth mentioning this in the Readme, for newbies, what am I. )
