### ISSUE TITLE
Execution error : can't set attribute

### ISSUE THREAD

**Issue by senhakan** [albertodonato/query-exporter#106]
Hello,
when i run the app, i getting "can't set attribute" error, os centos 8.
I couldn't solve the problem, can you help me?

[root@db ~]# query-exporter /root/test.yml
can't set attribute
[root@db ~]# sqlite3 clients.db "select id from clients"
0664344a71314bd095ffd1ce0733e968
08635D46-34B0-4AFC-8749-8888B360575C
0b75e6807cbd4f6c91093941d0481b8d

[root@db ~]# cat test.yml
databases:
  db:
    dsn: sqlite:///root/clients.db

metrics:
  clientid:
    type: gauge
    description: clientid_desc
    labels: [client_id]

queries:
  query1:
    interval: 5
    databases: [db]
    metrics: [clientid]
    sql:
      SELECT id
        FROM clients

**Comment by albertodonato** [comment]
What version are you using? This seems to be the same as https://github.com/albertodonato/query-exporter/issues/105, which was fixed in 2.8.1
