### ISSUE TITLE
Function Sequence Error

### ISSUE THREAD

**Issue by mhamil55** [albertodonato/query-exporter#11]
My exporter was working last week but for some reason now I am getting errors like:

2019-08-07 14:09:38,634 - ERROR - query-exporter - query "query2" on database "*my database*" failed: (pyodbc.Error) ('HY000', '[HY000] [Microsoft][ODBC SQL Server Driver]Connection is busy with results for another hstmt (0) (SQLExecDirectW)')

2019-08-07 14:09:38,650 - ERROR - query-exporter - query "query1" on database "*MY Database" failed: (pyodbc.Error) ('HY010', '[HY010] [Microsoft][ODBC SQL Server Driver]Function sequence error (0) (SQLFetch)')
(Background on this error at: http://sqlalche.me/e/dbapi)

**Comment by albertodonato** [comment]
Reading https://social.msdn.microsoft.com/Forums/sqlserver/en-US/d51d71e3-512f-4143-a8db-3e39286cb746/microsoftodbc-sql-server-driverconnection-is-busy-with-results-for-another-hstmt this might be an issue with old versions of SQLServer.

Could you provide a bit more details on what version of SQL server are you using, and the query-exporter configuration you're using?

**Comment by mhamil55** [comment]
I'm using a version 14.0.17285.0. I see that there is an update. I will try that and let you know how it goes.

**Comment by mhamil55** [comment]
I'm using a version 14.0.17285.0. I see that there is an update. I will try that and let you know how it goes. And by exporter configuration, what do you mean?

**Comment by albertodonato** [comment]
At the very least, whether you're performing more than one query on the same database.
That seems to be the problem, in the case where SQLServer doesn't support multiple cursors on the same connection.

**Comment by mhamil55** [comment]
Do you have any advice on what I should do if all the data I need for my metrics are all on the same database.

**Comment by albertodonato** [comment]
Are you making more than one query on the same database? It seems this could be the issue. I'm not sure if it's an issue in query-exporter, SQLServer or the driver.

Could you paste a traceback when running the program with -LDEBUG ? Please sanitize any private info.

**Comment by mhamil55** [comment]
I've changed my query and haven't had any more problems
