### ISSUE TITLE
Unable to use dummy columns to select statements (Oracle)

### ISSUE THREAD

**Issue by Tedigom** [albertodonato/query-exporter#113]
**Installation details**

Oracle Database 11g Enterprise Edition Release 11.2.0.4.0
query-exporter 2.8.0 ( docker )

**Describe the bug**
I've got an issue to use dummy columns to select statements in Oracle

Here's my config file

~~~
databases:
  oracle:
    dsn: oracle://

metrics:
  kafka_unpublished:
    type: gauge
    description : Number of rows Kafka didn't published
    labels: [tableName]

queries:
  kafka_unpublished:
    databases: [oracle]
    metrics:
      - kafka_unpublished
    sql: >
            SELECT COUNT(*) AS kafka_unpublished,'TEST01' as tableName FROM test01 WHERE del_yn='N'
~~~

and Here's the log from query-exporter
~~~
2022-04-07 05:23:46,973 - ERROR - query-exporter - query "kafka_unpublished" on database "oracle" failed: Wrong column names from query
2022-04-07 05:23:46,973 - DEBUG - query-exporter -   File "/virtualenv/lib/python3.8/site-packages/query_exporter/db.py", line 317, in execute
    return query.results(await QueryResults.from_results(result))
  File "/virtualenv/lib/python3.8/site-packages/query_exporter/db.py", line 210, in results
    raise InvalidResultColumnNames()
~~~

I can execute my query in my Oracle database, but not in query-exporter.
I tried to change apostrophe as double quote ('TEST01' as "TEST01") but it didn't worked either. 
Is there any guidance to use dummy columns in Select statement?

**Comment by albertodonato** [comment]
if you run the query manually, does the case for the column name get respected? I.e., do you get `tableName` or `tablename` as column name?

Also, could you try using something like `table_name` with query-exporter?
I suspect it might be that the DB driver is not keeping the column case.

**Comment by Tedigom** [comment]
thanks for your comment. 
you were right. the DB driver doesn't keep the column case, 'tablename'
