### ISSUE TITLE
Getting exception when no data on enum metric type output

### ISSUE THREAD

**Issue by avie208** [albertodonato/query-exporter#114]
[](https://user-images.githubusercontent.com/28735696/162161192-6296dd5a-8014-4228-b560-b0a4179f8742.png)Hi team,
When using declared eunm metric type , im receiving an exception if no results on output.
The exception is:

> Task exception was never retrieved
future: <Task finished name='Task-141282' coro=<QueryLoop._execute_query() done, defined at /virtualenv/lib/python3.8/site-packages/query_exporter/loop.py:187> exception=ValueError('0.0 is not in list')>
Traceback (most recent call last):
File "/virtualenv/lib/python3.8/site-packages/query_exporter/loop.py", line 208, in _execute_query
self._update_metric(
File "/virtualenv/lib/python3.8/site-packages/query_exporter/loop.py", line 260, in _update_metric
getattr(metric, method)(value)
File "/virtualenv/lib/python3.8/site-packages/prometheus_client/metrics.py", line 712, in state
self._value = self._states.index(state)
ValueError: 0.0 is not in list

Im using helm chart.
This is the query:

> gw_critical_sla_20d_type_3_count:
interval: 5m
databases: [db-server]
metrics: [query_result_gw_critical_sla_20d_type_3_count,endpoint_gw_critical_sla_20d_type_3_count,scan_type_gw_critical_sla_20d_type_3_count]
sql: |
select count(*) as query_result_gw_critical_sla_20d_type_3_count, endpoint as endpoint_gw_critical_sla_20d_type_3_count, scan_type as scan_type_gw_critical_sla_20d_type_3_count
from scan_request
where scan_progress in (10, 15) and scan_type in (3) and last_updated > '2021-11-18' and last_updated < date_sub(now(), interval 20 day);

This is the metrics:

> query_result_gw_critical_sla_20d_type_3_count:
type: gauge
labels: [endpoint_gw_critical_sla_20d_type_3_count,scan_type_gw_critical_sla_20d_type_3_count]
endpoint_gw_critical_sla_20d_type_3_count:
type: enum
states: ["domain1.com","domain2.com"]
scan_type_gw_critical_sla_20d_type_3_count:
type: gauge

The exception doset occur when results of enum metric is exist.
This is the actual result from the database:
![image](https://user-images.githubusercontent.com/28735696/162162778-3e9aa527-fdcd-419f-b169-dded56463eba.png)

Please help
Kind regards!
Avi

**Comment by albertodonato** [comment]
This doesn't seem to be an exporter problem, you need to change your query to always return a numeric value if a row is returned.

In this case you can probably do something like `COALESCE(columname, 0)` for each one so that it returns 0 instead of NULL.

**Comment by avie208** [comment]
Thanks @albertodonato !
can you please tell me how should i use it on my query?
e.g for this one i mentioned above:

> gw_critical_sla_20d_type_3_count:
interval: 5m
databases: [db-server]
metrics: [query_result_gw_critical_sla_20d_type_3_count,endpoint_gw_critical_sla_20d_type_3_count,scan_type_gw_critical_sla_20d_type_3_count]
sql: |
select count(*) as query_result_gw_critical_sla_20d_type_3_count, endpoint as endpoint_gw_critical_sla_20d_type_3_count, scan_type as scan_type_gw_critical_sla_20d_type_3_count
from scan_request
where scan_progress in (10, 15) and scan_type in (3) and last_updated > '2021-11-18' and last_updated < date_sub(now(), interval 20 day);

Thanks!
Avi

**Comment by albertodonato** [comment]
I meant something like:
```
select count(*) as query_result_gw_critical_sla_20d_type_3_count, coalesce(endpoint, 0.0) as endpoint_gw_critical_sla_20d_type_3_count, coalesce(scan_type, 0.0) as scan_type_gw_critical_sla_20d_type_3_count
from scan_request ...
```

**Comment by avie208** [comment]
Thanks you so much @albertodonato !
Exception is gone and all good !
Avi
