### ISSUE TITLE
Query exporter keep report on old metrics and not refreshing results

### ISSUE THREAD

**Issue by avie208** [albertodonato/query-exporter#115]
Hi team
we experience a weird behaviour which prometheus show old metrics values which didnt refreshed, we are running multiple queries on multiple databases using helm chart.
The metrics are refreshed and updated on the prometheus only after restarting the query exporter pod.
please assist , we keep getting false alerts on our production env.
Thanks,
Avi

**Comment by albertodonato** [comment]
Can you please attach your config and logs from running the exporter with `-L DEBUG`?

**Comment by avie208** [comment]
Hi @albertodonato 
turned out i had to add the expiration parameter which solved it, the query exporter kept on saving old metrics results and expiration parameter solve it, i set it to 10 min while interval of the check is 5 min.
