### ISSUE TITLE
How to query from Oracle DB with no access to config oracle-instantclient 

### ISSUE THREAD

**Issue by 2029899** [albertodonato/query-exporter#116]
I have no sudo access to config the oracle-instantclient, and to ask Admin team for configuration will take a very long and complex Change process.
I can run query-exporter in my own /home path and also downloaded oracle-instantclient-19.11.0.0.0 in same path.
Is there any method allowed me to config the client lib within my own /home path ?
many thanks

**Comment by albertodonato** [comment]
The easiest would be to install query-exporter and its dependencies (including `cx_oracle`) in a virtualenv, and make the instaclient library available by adding the dir to `LD_LIBRARY_PATH`

**Comment by 2029899** [comment]
@albertodonato Thanks a lot. It works by adding instantclient path into LD_LINRARY_PATH
