### ISSUE TITLE
docker+mssql not work

### ISSUE THREAD

**Issue by km5210** [albertodonato/query-exporter#117]
Hi, I'm facing an issue.

my config is:
 dsn: mssql+pyodbc://sa:1qaz%40WSX@172.60.30.11:1433/master?MARS_Connection=yes&driver=ODBC+Driver+17+for+SQL+Server

error:
ERROR - query-exporter - error from database "db": (pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 (10054) (SQLDriverConnect)')

SOURCE: RHEL 8.4
DEST: WinServer2012R2,MSSQL:2014 SP3
Help me, please.

**Comment by albertodonato** [comment]
This seems related to https://github.com/mkleehammer/pyodbc/issues/610

**Comment by albertodonato** [comment]
Can you please test again with 2.9.0?

**Comment by albertodonato** [comment]
Closing this since it has not seen activity in a while. Please reopen with details if it still applies.
