### ISSUE TITLE
need to know which type of metric to use

### ISSUE THREAD

**Issue by avie208** [albertodonato/query-exporter#119]
Hi team, 
I need to know which type of metric should i use if my results are per the image below:
![image](https://user-images.githubusercontent.com/28735696/163823313-0c2ba192-7740-49b2-b6e3-49125696eafe.png)
Thanks!

**Comment by albertodonato** [comment]
Hi, that screenshot doesn't say much about what you're trying to measure and how.

Please see https://prometheus.io/docs/concepts/metric_types/ for a description of what metrics are supported by Prometheus and appropriate use for each type.

**Comment by avie208** [comment]
Sorry @albertodonato not posting all the info, but i assume this kind of metric is not allowed, its a list of number.
This is my query:

> select count(*) as query_result_stage_core_gw_dependent_query_15_autoscans_count, substring_index(group_concat(sr.id SEPARATOR ','), ',', 10) as request_ids_stage_core_gw_dependent_query_15_autoscans
      from scan_request sr, url_scan_request usr
      where usr.scan_request_id=sr.id
      and scan_type in (6,7,9)
      and scan_progress = 15
      and usr.is_original_url = 1
      and usr.connection_info is null
      and last_updated > '2021-11-18'
      and last_updated < date_sub(now(), interval 90 MINUTE);
