### ISSUE TITLE
Is it possible to change where the metrics are exposed to?

### ISSUE THREAD

**Issue by mhamil55** [albertodonato/query-exporter#12]
My job wants the metrics to be exposed to our network's website instead of being a localhost. Is it possible I can change the website from being localhost to our server the query-exporter is being run on?

**Comment by albertodonato** [comment]
You can use the `-H`/`--host` comandline arg to change the address the service listens on. You can set it to the hostname of the machine, or just to `0` (or `::` IPv6) to bind all addresses

**Comment by mhamil55** [comment]
Could you give me an example of what I should put in the command line? I am getting a 11001  getaddrinfo failed error

**Comment by albertodonato** [comment]
just use `-H 0` and it will make it listen on all addresses of the machine
