### ISSUE TITLE
Memsql / Mysql

### ISSUE THREAD

**Issue by mcarol44** [albertodonato/query-exporter#120]
**Describe the bug**
2022-04-20 12:32:14,720 - ERROR - query-exporter - error from database "sdba": 'AsyncioEngine' object has no attribute 'hide_parameters'.

A clear and concise description of what the bug is and when it happens.
everything had been working great and they upgraded the memsql and now Im getting this error. 

2022-04-20 12:32:14,720 - ERROR - query-exporter - error from database "sdba": 'AsyncioEngine' object has no attribute 'hide_parameters'.

**Installation details**

- operating system: [OS and version]
- query-exporter installation type:
  - pip: [output from `pip list`]
  - docker image: [`<image tag>`]
  - snap: [output from `snap info query-exporter`]

**To Reproduce**

If possible, please provide detailed steps to reproduce the behavior:

1. Config file content (redacted of secrets if needed)

2. Ran query-exporter with the following command line ...

3. Got the error when ...

**Comment by mcarol44** [comment]
2022-04-20 12:32:14,720 - ERROR - query-exporter - error from database "sdba": 'AsyncioEngine' object has no attribute 'hide_parameters'.

**Comment by albertodonato** [comment]
Can you please provide information on how are you running query-exporter (snap, docker, pip,...)?

**Comment by mcarol44** [comment]
pip and here is how I start it up
query-exporter sdb_exporter_e1_config.yml -H 0.0.0.0 -p 9561 &

**Comment by mcarol44** [comment]
they upgraded from memsql version 7.1 to 7.5. I've tried connecting to a few different 7.5 versions and I'm getting the same error but when I try to connect to 7.1 everything works great.

**Comment by albertodonato** [comment]
Can you paste the output of `pip list`?

**Comment by mcarol44** [comment]
pip list
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.12
click              8.0.4
dataclasses        0.8
Flask              2.0.3
homebrew           0.2.5
httplib2           0.20.2
idna               3.3
importlib-metadata 4.8.3
itsdangerous       2.0.1
Jinja2             3.0.3
jsonlib-python3    1.6.1
MarkupSafe         2.0.1
netcat             0.0.1a0
pip                21.3.1
pyodbc             4.0.32
pyparsing          3.0.7
python-dotenv      0.19.2
pytz               2022.1
requests           2.27.1
setuptools         39.2.0
typing_extensions  4.1.1
urllib3            1.26.9
Werkzeug           2.0.3
zipp               3.6.0

**Comment by mcarol44** [comment]
ps -ef | grep query
oracle     540     1  0 Apr18 ?        00:17:20 /usr/local/bin/python3.8 /usr/local/bin/query-exporter postgres_exporter_e3_config.yml -H 0.0.0.0 -p 9563
grafana   1076     1  0 Mar04 ?        00:04:25 /usr/local/bin/postgres_exporter --extend.query-path=/apps/pg_exporter/queries.yaml --disable-settings-metrics --exclude-databases=edb,test,suvkum --auto-discover-databases
oracle    6072     1  0 Mar28 ?        00:08:56 /usr/local/bin/python3.8 /usr/local/bin/query-exporter ggmonitor.yml -H 0.0.0.0 -p 9570
oracle   17394     1  1 15:37 ?        00:00:15 /usr/local/bin/python3.8 /usr/local/bin/query-exporter sdb_exporter_e2_config.yml -H 0.0.0.0 -p 9564
oracle   27261 25853  0 15:58 pts/0    00:00:00 grep --color=auto query

**Comment by mcarol44** [comment]
the query exporter is running on a physical server with a local install I believe

**Comment by albertodonato** [comment]
That pip output doesn't seem to match the query-exporter installation, as it doesn't list query-exporter itself nor many of its dependencies (e.g. SQLAlchemy, prometheus_client, ...). I suspect dependencies got upgraded to some version that's incompatible with query-exporter (likely sqlalchemy or sqlalchemy_aio), but you need to find where query-exporter is looking for dependencies (system-wide, some virtualenv), depending on the way it was installed

**Comment by albertodonato** [comment]
Closing this since it looks like a dependencies issue, please reopen if it still happens with a clean dependency set.
