### ISSUE TITLE
Update Dockerfile to fix CRITICAL vulnerabilities linked to the used version of the base image

### ISSUE THREAD

**Issue by khaoulaB1** [albertodonato/query-exporter#122]
**Is your feature request related to a problem? Please describe.**

Using python:3.8-slim-buster as build image is provoking security issues some of them are CRITICAL vulnerabilities, bellow you will find a trivy scan for adonato/query-exporter:2.7.0 
![image](https://user-images.githubusercontent.com/47610975/165757972-3a5cbd8d-314d-412d-a353-53eea1ece337.png)

  
**Describe the solution you'd like**
Changing the used build image to python:alpine will solve secutiry critical vulnerabilities, below the trivy scan :
![image](https://user-images.githubusercontent.com/47610975/165758904-84aac2aa-fe49-4d52-948c-c6d0f6ceebfb.png)

**Comment by albertodonato** [comment]
2.8.3 is now bards on python-3.10-slim (based on debian 11)
