### ISSUE TITLE
Counters do not behave in a useful manner

### ISSUE THREAD

**Issue by mbailey** [albertodonato/query-exporter#124]
I like this project and didn't want to have to write it myself. :-)

There's a problem with Counters though: Counters increase by the value read from the database every time query-compose queries the database.

I can't think of a use case suited to this behaviour. It would be hard to write a query that takes into account the time it is run and avoids under/over counting items. It makes more sense to set the Counter value to the result of the DB query.

I know how this behaviour came to be in query-exporter. The project uses the instrumentation from the python client which only allows a value to be incremented, not set. The instrumentation is not intended for exporters. 

In the Prometheus docs for writing exporters it says,

> When implementing the collector for your exporter, you should never use the usual direct instrumentation approach and then update the metrics on each scrape.
> - [Writing Exporters](https://prometheus.io/docs/instrumenting/writing_exporters/#collectors)

They recommend using creating new metrics each time (and in python using [custom collectors](https://github.com/prometheus/client_python#custom-collectors)).

My python is rusty but I'll read through and try to get an idea how hard this would be to change.

**Comment by BulbaWarrior** [comment]
Is anything going to be done with this issue? Current `counter` logic is very cumbersome and using `gauges` is not a real solution. How about adding an extra configuration field to switch between new and old counter logic to avoid breaking changes?

**Comment by albertodonato** [comment]
Sorry, for the late response, I'm taking a look at this, I agree counters which get set from the result are more useful in general.

I'll add support for this behavior with a flag, possibly making a major release where the default is to set, but increment will be available through a flag.
