### ISSUE TITLE
Hive / Hadoop Queries

### ISSUE THREAD

**Issue by mcarol44** [albertodonato/query-exporter#125]
**Is your feature request related to a problem? Please describe.**
I have a Hive Database that we use for Hadoop. 
**Describe the solution you'd like**
Is there an exporter or driver I could use with Query Exporter to query the Hive DB. 
**Describe alternatives you've considered**
If we can't do this with Query Exporter is there an alternate solution I could use. 
**Additional context**

**Comment by albertodonato** [comment]
Hi, I don't have experience with Apache Hive, but looking at https://superset.apache.org/docs/databases/hive/ you can use pyhive to use it through sqlalchemy (which query-exporter uses).
This is not included in the offical snap or docker image, so you'll have to use your own env.
