### ISSUE TITLE
Update sqlalchemy to fix vulnerablities

### ISSUE THREAD

**Issue by masterkidan** [albertodonato/query-exporter#128]
**Describe the bug**

It looks like the version of sqlalchemy that is being used by query-exporter is having some vulnerabilities https://github.com/sqlalchemy/sqlalchemy/issues/5557 that is getting caught by security tooling. As the downstream bug is fixed, is it possible to update the version of sqlalchemy this repo is using?

**Installation details**

- operating system: Debian 11
- query-exporter installation type:
  - docker image: 2.8.1
**To Reproduce**

If possible, please provide detailed steps to reproduce the behavior:

1. Config file content (redacted of secrets if needed)
N/A
2. Ran query-exporter with the following command line ...
N/A
3. Got the error when ...
N/A

**Comment by albertodonato** [comment]
I've released 2.8.3 with an updated docker image with latest dependencies.
