### ISSUE TITLE
Question: MYSQL Connect with TLS/SSL (secure way)

### ISSUE THREAD

**Issue by bcarranza** [albertodonato/query-exporter#132]
Hi Community, 
Is it possible to connect to mysql through by tls/ssl with certification in order to avoid setting require_secure_transport  = OFF in AWS RDS MySQL.!!?

**Comment by lchopfpt** [comment]
I did this by using a .my.cnf file on the system. 
The .my.cnf includes the username, password, and CA path.
If using Docker, I used docker volumes to mount the file as /root/.my.cnf

**Comment by albertodonato** [comment]
Thanks @lchopfpt for the answer. Can this be closed now?

**Comment by albertodonato** [comment]
I'll close the issue, feel free to reopen in case it's not solved.
