### ISSUE TITLE
[Docker] module "pymssql" not found

### ISSUE THREAD

**Issue by wthee** [albertodonato/query-exporter#140]
**Describe the bug**
When using mssql+pymssql to connect mssql 

**Installation details**
docker adonato/query-exporter:latest

**To Reproduce**
connect mssql use mssql+pymssql://

**Comment by albertodonato** [comment]
It should be possible to connect to MSSQL via just `mssql://`, can you try that?

**Comment by wthee** [comment]
> It should be possible to connect to MSSQL via just `mssql://`, can you try that?

I tried. This error occurred
**[Driver Manager]Data source name not found, and no default driver specified**
This means that additional drivers must be installed

**Comment by wthee** [comment]
After executing "pip install pymssql" in the docker container, mssql+pymssql works
