### ISSUE TITLE
The schedule debug

### ISSUE THREAD

**Issue by ilanni2460** [albertodonato/query-exporter#142]
First of all, thank you very much, such a good tool.

During my use, I found that the schedule execution every minute or every 5 minutes is ok, but if it is executed to a specific time, it will not take effect.

The schedule executes sql at 10:05 every night, but it does not take effect, and no information is printed in the debug log.

query-exporter startup command:
`docker run -dit --restart always --name query_exporter -p 9560:9560 -v /data/query_exporter/config.yaml:/config.yaml adonato/query-exporter -L DEBUG`

The content of the config.yaml file is as follows:

`databases:
  dft_mysql:
    dsn: mysql://XXX:P@XXXX@XXXXX:3306/XXX
    keep-connected: true
    labels:
      env: UAT

metrics:
  gl_batch_ncc_file:
    type: gauge
    description: 跑批所需凭证文件

queries:
  gl_batch_ncc_file:
    timeout: 1
    schedule: "05 22 * * *"
    databases: [dft_mysql]
    metrics:
      - gl_batch_ncc_file
    sql: |
      SELECT count(*) as gl_batch FROM transfer WHERE sender LIKE '%ABC%';`

![2023-03-24_160451](https://user-images.githubusercontent.com/5058391/227461142-fe4f47a5-19dc-4726-af3d-4db3d9989e5d.png)

**Comment by ilanni2460** [comment]
It has been solved, the docker mode needs to be added to localtime.

`docker run -dit --restart always --name query_exporter -p 9560:9560 -v /data/query_exporter/config.yaml:/config.yaml -v /etc/localtime:/etc/localtime:ro adonato/query-exporter -L DEBUG`

**Comment by albertodonato** [comment]
Thanks for reporting the issue and solution.
Without passing `/etc/localtime`, does the query get executed at the indicated time in UTC ?

**Comment by ilanni2460** [comment]
@albertodonato Sorry, I haven't tested this yet. The guess should be ok, after all, it is ok to use localtime.
