### ISSUE TITLE
Is it possible to add lable function for each individual metrics under the metrics project

### ISSUE THREAD

**Issue by ilanni2460** [albertodonato/query-exporter#144]
Is it possible to add lable function for each individual metrics under the metrics project, this requirement is to query the same database, but there are multiple queries to distinguish different metrics

**Comment by albertodonato** [comment]
Hi, could you please explain your use case? Could you provide an example database schema and what metrics/queries you would want to extract?

**Comment by albertodonato** [comment]
Given that labels are populated from the query result, it should be possible to write the query (or use a stored procedure which contains the desired logic) to return specific labels for specific results.

Closing this one, please reopen with a detailed example if the suggestion doesn't fit the need.
