### ISSUE TITLE
Log column names in the InvalidResultColumnNames error

### ISSUE THREAD

**Issue by TommyDew42** [albertodonato/query-exporter#149]
Happy to work on this issue if we find this feature desirable.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Log column names in the InvalidResultColumnNames error. 
Now we don't have the wrong column names when we [log](https://github.com/albertodonato/query-exporter/blob/9aa30925b65ec4b26be5052444124c4274cd0f3a/query_exporter/db.py#L206-L207) the error:
```
query "<query-name>" on database "<db-name>" failed: Wrong column names from query
```

**Describe alternatives you've considered**

It would be great if we can have the columns in the log:
```
query "<query-name>" on database "<db-name>" failed: Wrong column names from query. The result column names: <column names in the result>
```

**Additional context**
I got this error but i was really confused what was wrong cuz indeed nth was wrong in my sql query. It turned out my column name was too long so postgres cut it into a shorter name in the result.

**Comment by albertodonato** [comment]
makes sense, I've added details to the error, thanks
