### ISSUE TITLE
ability to set port #

### ISSUE THREAD

**Issue by elasticdotventures** [albertodonato/query-exporter#153]
**Is your feature request related to a problem? Please describe.**
We use AWS ECS, and terraform and we have little control over where containers are deployed. 

**Describe the solution you'd like**
I'd like to be able to set the the port # on the command line, and not be forced to use 9560

**Describe alternatives you've considered**
I'm going to investigate submitting a PR. 

**Additional context**
👋

**Comment by albertodonato** [comment]
As show in the help, you can set the port:  `-p PORT, --port PORT  port to run the webserver on (default: 9560)`
