### ISSUE TITLE
 When running inside a Kubernetes pod, the container is failing to retrieve the latest updates from configmap.yaml.

### ISSUE THREAD

**Issue by mohan-s-gopal** [albertodonato/query-exporter#161]
**Describe the bug**
The query exporter stores custom SQL script configurations in the [config.yaml](https://github.com/albertodonato/query-exporter/tree/main#configuration-file-format) file, which is created as a ConfigMap. This ConfigMap is then mounted as a [volume](https://github.com/makezbs/helm-charts/blob/main/charts/query-exporter/templates/deployment.yaml#L91) into the Kubernetes pod. 

When any updates are made to the ConfigMap, the changes are reflected in the mounted volumes. 

However, the application remains unaware of the latest `config.yaml` changes until the pod is reloaded or restarted. Due to this behavior, the pod will not receive the most recent configuration until it is restarted.

**Installation details**

- query-exporter installation type:
  - docker image: [`adonato/query-exporter:2.7.0`]

**To Reproduce**

To deploy the query-exporter using the Helm chart:

1. Ensure that the Helm chart includes the following components:

- deployment.yaml for the application deployment.
- configmap.yaml containing the configuration file content.

2. After the initial deployment, everything appears to be functioning correctly, and the application is running as expected.

3.  However, when updating the ConfigMap, the application inside the pod does not recognize the changes, and it continues to operate with the previous configuration from the ConfigMap.

**Comment by albertodonato** [comment]
I think this should be reported in the [helm chart](https://github.com/makezbs/helm-charts/tree/main/charts/query-exporter).
I don't know much about Helm, but from a [quick searcht](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) this looks possible.
