### ISSUE TITLE
Add a builtin metric of query_timestamp - reporting last time query_exporter ran the query

### ISSUE THREAD

**Issue by lchopfpt** [albertodonato/query-exporter#178]
**Is your feature request related to a problem? Please describe.**
As an operator, I need to know when the last query ran, so I can be sure I have up to date information.   This is particularly helpful if perhaps there's an issue with query_exporter, the db connection or the query itself.  

**Describe the solution you'd like**
Add a builtin metric for each query that is the "last query run time", something like query_timestamp.

**Describe alternatives you've considered**
I have a work around by adding to add as a field for each of my queries... This doesn't always make sense though.

**Comment by albertodonato** [comment]
Thanks for the suggestion, this is now available in main.
