### ISSUE TITLE
Query result count error if fields don't have unique names

### ISSUE THREAD

**Issue by albertodonato** [albertodonato/query-exporter#18]
The following error

 ```
2019-12-23 11:26:17,097 - ERROR - query-exporter - query "query3" on database "db3" failed: Wrong result count from query: expected 2, got 1
```

happens if columns don't have unique names (e.g. when automatically named after functions):

```
  query3:
    interval: 10
    databases: [db3]
    metrics: [metric1, metric2]
    sql: |
      SELECT floor(random() * 100 + 1)::int,
             floor(random() * 100 + 1)::int
```

(both columns are named `floor` in Postgres)

**Comment by albertodonato** [comment]
Workaround is to name columns explicitly

**Comment by Elisi2020** [comment]
Hi Alberto 
many thanks for the library I'm struggling with the same error, and could not find the issue. Can you please advise?
metrics:
  metric1:
    type: gauge
    description: A sample gauge

queries:
  query1:
    interval: 60
    databases: [db1]
    metrics: [metric1]
    sql: |
             select r.host, count( distinct r."StudyID") as "#Studies" from receivedresults r
             where
             r.host = 'haemek'
             and r."timestamp"::date >= current_date-30
             group by r.host

ERROR - query-exporter - query "query1" on database "db1" failed: Wrong result count from query: expected 1, got 2

**Comment by albertodonato** [comment]
Since version 2.0.0 column names from query results need to match metric/label names (see
https://github.com/albertodonato/query-exporter/blob/master/CHANGES.rst#v200---2020-02-02 for details).

You need to return only the metric value from the query, and alias it `AS metric1`

**Comment by Elisi2020** [comment]
Wow such a quick answer THANKS !!! . I'm sorry but with the below changes I'm still getting the same error
             select Upper(r.host), count( distinct r."StudyID") as  metric1 from receivedresults r
             where
             host not like 'ip-%'
             and host not like 'test'
             and r."timestamp"::date >= current_date-30
             group by Upper(r.host)

**Comment by albertodonato** [comment]
What do you need the host column for? You're using a gauge, so effectively the value will be just the one of the last row.
Unless you use the host as a label, in which case you need to declare it in the metric and match the names of the columns to metric and label names

**Comment by albertodonato** [comment]
as long as you define a single query statement that returns the expected columns and is supported by your database backend, it should work fine
