### ISSUE TITLE
Password with ':' fails to authenticate to postgres

### ISSUE THREAD

**Issue by karolvargas** [albertodonato/query-exporter#196]
**Describe the bug**

A clear and concise description of what the bug is and when it happens.

**Installation details**

- operating system: linux k8s
- query-exporter installation type: docker

**To Reproduce**

If possible, please provide detailed steps to reproduce the behavior:

1. Config file content (redacted of secrets if needed)
databases:
  billing:
    dsn: env:BILLING_CONNECTION_STRING
    keep-connected: false
  documents:
    dsn: env:DOCUMENTS_CONNECTION_STRING
    keep-connected: true
  jobs:
    dsn: env:JOBS_CONNECTION_STRING
    keep-connected: false
  legends:
    dsn: env:LEGENDS_CONNECTION_STRING
    keep-connected: false
  messages:
    dsn: env:MESSAGES_CONNECTION_STRING
    keep-connected: false
  notifications:
    dsn: env:NOTIFICATIONS_CONNECTION_STRING
    keep-connected: false
  wunder:
    dsn: env:WUNDER_CONNECTION_STRING
    keep-connected: false

2. Ran query-exporter with the following command line ...
ran with terraform in a k8s deployment

3. Got the error when ...
deployment spun up pod. Password fails authentication because there is special characters

**Comment by karolvargas** [comment]
https://stackoverflow.com/questions/1423804/writing-a-connection-string-when-password-contains-special-characters This might be what you are missing

**Comment by albertodonato** [comment]
as mentioned in the doc, you need to url-encode the DSN, or use the key/value form:

>Note that in the string form, username, password and options need to be URL-encoded, whereas this is done automatically for the key/value form.
