### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by NelsonFigueira** [albertodonato/query-exporter#2]
Hi,
could you improve the documentation specially about the configuration file , is this a yml ?
And also how to start the exporter passing the config file? 

Thanks
Nelson

**Comment by NelsonFigueira** [comment]
Hi, 

I'm strying to start the exporter in the following way but I get an exception. 
I'm am doing it the right way ? Or is there some other issue with this toolrack module? 

@query_exporter > python3.7 ./main.py .config.yml
Traceback (most recent call last):
  File "./main.py", line 5, in <module>
    from toolrack.script import ErrorExitMessage
ModuleNotFoundError: No module named 'toolrack'

Thanks
Nelson

**Comment by albertodonato** [comment]
Hi @NelsonFigueira,
you need to install query-exporter with its dependencies.
You can `python3.7 setup.py install` in a virtualenv or install it system-wide or get it from PyPI via `pip install query-exporter`.

Alternatively, if you're on a supported platform, you can install it from snaps via `sudo snap install query-exporter`.

After installation, a `query-exporter` command will be available. The configuration file to pass is in YAML format as described on the readme.
