### ISSUE TITLE
Wrong result count from query - too many "AS" used in query?

### ISSUE THREAD

**Issue by arope28** [albertodonato/query-exporter#20]
I am attempting to pull data out of a server to get the value of some fields that were recorded the previous day. In taking a deeper look, I am wondering if the script is counting the number of "AS" statements in the query in order to determine the expected number of results from the query. 

Error: 
`2020-01-17T18:59:14Z query-exporter.daemon[9204]: 2020-01-17 18:59:14,244 - ERROR - query-exporter - query "ob_stats" on database "pg" failed: Wrong result count from query: expected 8, got 3`

config.yaml is set up as follows:
```
metrics:
  ob_avg_elapsed_time:
    type: gauge
    labels: [rd, avg]
  ob_max_elapsed_time:
    type: gauge
    labels: [rd, max]
  ob_min_elapsed_time:
    type: gauge
    labels: [rd, min]

queries:
  ob_stats:
    interval: 1d
    databases: [pg]
    metrics: [ob_avg_elapsed_time, ob_max_elapsed_time, ob_min_elapsed_time]
    sql: >
      SELECT
        coalesce(AVG(((EXTRACT(EPOCH FROM (CAST(_http_requests.completed_at AS TIMESTAMP) - _http_requests.created_at)) / (60.0 * 60 * 24)) * 86400)), 0) AS ob_avg_elapsed_time,
        coalesce(MAX(((EXTRACT(EPOCH FROM (CAST(_http_requests.completed_at AS TIMESTAMP) - _http_requests.created_at)) / (60.0 * 60 * 24)) * 86400)), 0) AS ob_max_elapsed_time,
        coalesce(MIN(((EXTRACT(EPOCH FROM (CAST(_http_requests.completed_at AS TIMESTAMP) - _http_requests.created_at)) / (60.0 * 60 * 24)) * 86400)), 0) AS ob_min_elapsed_time
      FROM public._http_requests _http_requests
      LEFT JOIN public._users _users ON (_http_requests.user_id = _users.id)
      LEFT JOIN public._sessions _sessions ON (_http_requests.session_id = _sessions.session_id)
      LEFT JOIN public._sites _sites ON (_http_requests.site_id = _sites.id)
      WHERE ((_http_requests.currentsheet IN ('ob/OrgBreakdown')) AND (_sites.name = 'team1')) and (CAST(TRUNC(EXTRACT(DAY FROM _http_requests.created_at)) AS INTEGER)) = (cast(TRUNC(extract(day from CURRENT_DATE - interval '1 DAY')) as INTEGER))
```

The result of the query run on its own is similar to the following:
``` 
ob_avg_elapsed_time | ob_max_elapsed_time | ob_min_elapsed_time
---------------------+---------------------+---------------------
                   0 |                   0 |                   0
```

**Comment by albertodonato** [comment]
Your metrics have dynamic labels defined, specifically `rd`, `avg`, `max`, `min`, so your query needs to also include values for those.
As mentioned in the doc, in this case you have to use aliases for fields that match both metrics and label names.

I'm not sure why the error is saying that it needs 8 columns, while it should be 7 (3 metrics + 4 labels). I tried a similar setup, and it does report 7:

```
databases:
  db:
    dsn: postgresql://ack:ack@localhost/ack

metrics:
  ob_avg_elapsed_time:
    type: gauge
    labels: [rd, avg]
  ob_max_elapsed_time:
    type: gauge
    labels: [rd, max]
  ob_min_elapsed_time:
    type: gauge
    labels: [rd, min]

queries:
  query:
    databases: [db]
    metrics: [ob_avg_elapsed_time, ob_max_elapsed_time, ob_min_elapsed_time]
    sql: |
      SELECT
        1.0 AS ob_avg_elapsed_time,
        1.0 AS ob_min_elapsed_time,
        1.0 AS ob_max_elapsed_time,
```

This will (correctly) error with `2020-01-17 23:59:55,251 - ERROR - query-exporter - query "query" on database "db" failed: Wrong result count from query: expected 7, got 3`

Adding values for labels as well fixes it:

```
queries:
  query:
    databases: [db]
    metrics: [ob_avg_elapsed_time, ob_max_elapsed_time, ob_min_elapsed_time]
    sql: |
      SELECT
        1.0 AS ob_avg_elapsed_time,
        1.0 AS ob_min_elapsed_time,
        1.0 AS ob_max_elapsed_time,
        'foo' AS rd,
        'bar' AS min,
        'baz' AS max,
        'bza' AS avg
```

Are you using the latest version? If not, could you try with that and adding values for labels?

**Comment by arope28** [comment]
You were absolutely correct, thank you. I was not accounting for the labels correctly in my queries. After upgrading to the latest version, and adding the labels  correctly via query, the application works perfectly. Thank you again.

**Comment by albertodonato** [comment]
No problem, happy to see there's no bug there :)
