### ISSUE TITLE
Bugs in Tag latest

### ISSUE THREAD

**Issue by pargolasghari** [albertodonato/query-exporter#203]
Hi guys,

I'm working on query exporter with the latest tag, but for the past two days, I haven't been able to deploy because I get this error:
Invalid database DSN: "clickhouse+native://user_name:password@host:port"

However, when I change it to 2.9.2, it works fine.

Can you please check the latest tag?

**Comment by albertodonato** [comment]
This should work with the latest 2.11.0 release
