### ISSUE TITLE
Wrong result count from query

### ISSUE THREAD

**Issue by imperatives** [albertodonato/query-exporter#22]
I am running into an issue with query count and unsure if this is a bug, required feature, or I am simply not grasping the query-exporter configuration correctly.  

```
metrics:
  wait_time:
      type: gauge
      description: Generic metric from v$waitclassmetric view in Oracle.
      lables: [wait_class]

queries:
  wait_time:
      interval: 15     
      databases: [oracle]
      metrics: [wait_time]
      sql: |

SELECT
n.wait_class as "WAIT_CLASS",
round(m.time_waited/m.INTSIZE_CSEC,3) as "WAIT_TIME"
FROM
v$waitclassmetric  m, v$system_wait_class n
WHERE
m.wait_class_id=n.wait_class_id AND n.wait_class != 'Idle'
```
This results in the following error: 
`ERROR - query-exporter - query "wait_time" on database "oracle" failed: Wrong result count from query: expected 1, got 2`

If I add another arbitrary metric I received an error indicating that a string from the wait_class view, which I have defined as a metric label is being treated as a second query value.
`exception=ValueError("could not convert string to float: 'Application'",)>`

In another prometheus database exporter tool there is a "field to append" option (e.g. fieldtoappend= "wait_class") used with these sorts of queries.

**Comment by albertodonato** [comment]
Can you try using lowercase aliases for column fields? (i.e. wait_class and
wait_time)

If that's the case, it might just be an issue with the error message not
being very helpful.

**Comment by imperatives** [comment]
Unfortunately it results in the same error.

**Comment by albertodonato** [comment]
oh, you have a typo in the config, "lables" vs "labels", so it's not
expecting a label.

**Comment by imperatives** [comment]
Wow...I feel a bit embarrassed, but am really grateful.  I spent a few hours trying to get the query working properly and never even bothered to look at the metric configuration carefully.  It is now working perfectly!  
`# HELP wait_time Generic counter metric from v$waitclassmetric view in Oracle.
# TYPE wait_time gauge
wait_time{database="oracle",wait_class="Other"} 0.001
wait_time{database="oracle",wait_class="Application"} 0.0
wait_time{database="oracle",wait_class="Configuration"} 0.0
wait_time{database="oracle",wait_class="Concurrency"} 0.0
wait_time{database="oracle",wait_class="Commit"} 0.0
wait_time{database="oracle",wait_class="Network"} 0.0
wait_time{database="oracle",wait_class="User I/O"} 0.0
wait_time{database="oracle",wait_class="System I/O"} 0.002`

Thank you for this great project.

**Comment by albertodonato** [comment]
No worries, I've been thinking about adding schema validation for the yaml config.
It would have been useful in this case to report the invalid keyword.

I'll have a look at adding the feature when I have a moment.

Glad it wasn't a bug in the end :)
