### ISSUE TITLE
(psycopg2.errors.SyntaxError) syntax error at or near ":"

### ISSUE THREAD

**Issue by lihaiswu** [albertodonato/query-exporter#24]
2020-01-31 21:00:29,509 - ERROR - query-exporter - query "pipeline_test_stats[params0]" on database "pg" failed: (psycopg2.errors.SyntaxError) syntax error at or near ":"
LINE 9: FROM pipeline INNER JOIN test ON :x INNER JOIN test_aggregat...

Seems similar issue at https://stackoverflow.com/questions/47190680/sqlalchemy-exc-programmingerror-psycopg2-programmingerror-syntax-error-at-or

**Comment by albertodonato** [comment]
Yes, this is closely related to https://github.com/albertodonato/query-exporter/issues/21#issuecomment-580810131

As a workaround, you should be able to use the `%(param)s` syntax.
I'll switch to use `text()` soon, at which point the `:param` syntax (and only that one) will work for all backends.

**Comment by lihaiswu** [comment]
@albertodonato  thanks for the quick fix.
