### ISSUE TITLE
Oracle exporter queries

### ISSUE THREAD

**Issue by msureshmsc** [albertodonato/query-exporter#3]
My data base is oracle. My requirement is alarms for : DB down, DB Slow, Some other Oracle erros like lack of table space and make a dashboard with the metrics.

I have done the below steps:

1.	Copied the source code from the URL: https://github.com/albertodonato/query-exporter
2. 	Entered into query_exporter folder
3.	Created config.yml file and script drafted as per format given in the github.
Questions:
1.	How to startup the oracle exporter?
2.	Do I need to touch any of the file with .py?  which means do I need to configure something in main.py or setup.py?

I have attached word document for your reference.

Please help to clarify my queries.

**Comment by albertodonato** [comment]
Hi @msureshmsc,
 you have to install query-exporter along with its dependencies for Oracle.
Specifically you can `pip install query-exporter SQLAlchemy[oracle]` and also install `cx_Oracle`

See details on https://docs.sqlalchemy.org/en/latest/dialects/oracle.html#module-sqlalchemy.dialects.oracle.cx_oracle

Unfortunately I don't know much about Oracle and I have no way of testing this myself, but as long as SQLAlchemy finds the required dependencies it should work.

**Comment by toimtoimtoim** [comment]
On Ubuntu 18.4 this is what you need to do:

```
sudo apt install python3-pip alien libaio1
pip3 install query-exporter SQLAlchemy[oracle]

# install 'cx_Oracle' See: https://cx-oracle.readthedocs.io/en/latest/installation.html#install-cx-oracle
sudo apt install alien libaio1
pip3 install cx_Oracle --upgrade

# download oracle-instantclient18.5-basic-18.5.0.0.0-3.x86_64.rpm  from Oracle site
sudo alien -i oracle-instantclient18.5-basic-18.5.0.0.0-3.x86_64.rpm

sudo sh -c "echo /usr/lib/oracle/18.5/client64/lib/ > /etc/ld.so.conf.d/oracle-instantclient.conf"
sudo ldconfig

# export LD_LIBRARY_PATH=/usr/lib/oracle/18.5/client64/lib:$LD_LIBRARY_PATH


cat > config.yml <<EOL
databases:
  db1:
    dsn: oracle+cx_oracle://user:password@localhost:1521/XE

metrics:
  metric1:
    type: gauge
    description: A sample gauge

queries:
  query1:
    interval: 5
    databases: [db1]
    metrics: [metric1]
    sql: SELECT 1 from dual
EOL

# start exporter
query-exporter config.yml

# check if it is working
curl http://127.0.0.1:9560/metrics
```

**Comment by albertodonato** [comment]
thanks @toimtoimtoim !

**Comment by 2029899** [comment]
> On Ubuntu 18.4 this is what you need to do:
> 
> ```
> sudo apt install python3-pip
> pip3 install query-exporter SQLAlchemy[oracle]
> 
> # install 'cx_Oracle' See: https://cx-oracle.readthedocs.io/en/latest/installation.html#install-cx-oracle
> sudo apt install alien libaio1
> pip3 install cx_Oracle --upgrade
> 
> # download oracle-instantclient18.5-basic-18.5.0.0.0-3.x86_64.rpm  from Oracle site
> sudo alien -i oracle-instantclient18.5-basic-18.5.0.0.0-3.x86_64.rpm
> 
> sudo sh -c "echo /usr/lib/oracle/18.5/client64/lib/ > /etc/ld.so.conf.d/oracle-instantclient.conf"
> sudo ldconfig
> 
> # export LD_LIBRARY_PATH=/usr/lib/oracle/18.5/client64/lib:$LD_LIBRARY_PATH
> 
> 
> cat > config.yml <<EOL
> databases:
>   db1:
>     dsn: oracle+cx_oracle://user:password@localhost:1521/XE
> 
> metrics:
>   metric1:
>     type: gauge
>     description: A sample gauge
> 
> queries:
>   query1:
>     interval: 5
>     databases: [db1]
>     metrics: [metric1]
>     sql: SELECT 1 from dual
> EOL
> 
> # start exporter
> query-exporter config.yml
> 
> # check if it is working
> curl http://127.0.0.1:9560/metrics
> ```

Hi @toimtoimtoim May I ask how to config the client lib if I have no sudo access and cannot ask admin help to config.

**Comment by aldas** [comment]
containers (docker) maybe? or  [fakeroot](http://manpages.ubuntu.com/manpages/trusty/man1/fakeroot-tcp.1.html) and install rpm with that?
