### ISSUE TITLE
Encrypt and decrypt connection string

### ISSUE THREAD

**Issue by stratewarius** [albertodonato/query-exporter#30]
Hi Alberto!
Improve field "dsn":
add possibility to encrypt and decrypt connection string.

**Comment by albertodonato** [comment]
Can you provide a bit more detail?
Why do you need it encrypted and how would you decrypt it?

**Comment by stratewarius** [comment]
I think it is not secure if in config password will be on plain text format. All security scanner will see it like vulnerability and it is a deficiency. Based on my previous experience.

**Comment by albertodonato** [comment]
You can have the dsn defined in an env variable (using `dsn: env:VARNAME`) which can be populated from whatever (including decrpyting a file) as `VARNAME=$(gpg --decrypt somefile)` or similar

**Comment by stratewarius** [comment]
Tnx u @albertodonato! I will close this issue.
