### ISSUE TITLE
Help wanted: Connect to Postgres using SSL certificates

### ISSUE THREAD

**Issue by lenalebt** [albertodonato/query-exporter#37]
Hi,
currently trying to connect to a postgres database that also uses client / server certificates. As far as I understand, I cannot add the ssl connection parameters to the DSN string with sqlalchemy. If I am wrong, I'd love to get some info about how to do it :).

Please explain how I can use it with client/server certificates (best would be an entry in the README) or add the possibility to configure ssl options explicitly.

**Comment by jeffeland** [comment]
@lenalebt by any chance, did you find out how to make a connection protected by SSL work. In my case, it's IBM but it may be similar to postgress.

**Comment by lenalebt** [comment]
Hey @jeffeland - no, sorry. I did not, but I also did not try very hard since I later on found out that we had a cluster-internal proxy that handled that SSL connection stuff that I could use. Still I'd feel better to directly connect via SSL... If you find out how to do it I'd be keen to know <3.

**Comment by albertodonato** [comment]
Hi, I've never used client/server certs with PostgreSQL myself, but I think you need to

- add `?sslmode=require` or `?sslmode=verify-full` to the DB DSN
- pass the client certificate/key via `PGSSLCERT`/`PGSSLKEY` env variables

This is all PostgreSQL specific, I have no idea about DB2.

**Comment by albertodonato** [comment]
@lenalebt could you provide an example of how is the server configured for certificates?

**Comment by lenalebt** [comment]
Hey, sorry - we used the cloudsql-proxy to connect. I did not set it up to handle the certificates directly.

**Comment by albertodonato** [comment]
I'm closing this, please reopen if further info/help is needed
