### ISSUE TITLE
Do i need to set timeout for query execution?

### ISSUE THREAD

**Issue by thePolly** [albertodonato/query-exporter#43]
Hello, i have a question - when DB query take too long time for execution does it impact all metrics return time. 
Do i need to set timeout for query execution to solve problem with long executing queries or does async/await already solves it?

**Comment by albertodonato** [comment]
Hi, can you explain your use case a bit better?
Are queries timing out, or do they just take a lot of time?
The fact that a query takes a long time shouldn't be an issue, but you'll want to set the interval for those queries to be longer than the time it takes.

The only case where a auery would block everything is if you don't set an interval, in which case every HTTP request will trigger those queries, and the endpoint would only return once queries return.

**Comment by thePolly** [comment]
Thank you for the fast reply! That answers my question.
