### ISSUE TITLE
mysql database / histogram

### ISSUE THREAD

**Issue by vargazs** [albertodonato/query-exporter#45]
I have an event_length table in my mysql database with a column event_length (int) containing the length of an event. There is an event_date (datetime) column with the timestamp when the event happens. 

I would like to create a histogram metric from this data. My config.yaml is the following:

=== config.yaml ===

databases:
  db1:
    dsn: mysql://xx_user_xx:xx_password_xx@xx_ip_xx:xx_port_xx/xx_database_xx

metrics:

  metric2:
    type: histogram
    description: A sample histogram
    buckets: [10, 20, 50, 100]

queries:

  query2:
    interval: 20
    databases: [db1]
    metrics: [metric2]
    sql: |
      SELECT event_length AS metric2 from event_length

=== config.yaml ===

The exporter works excellent and I can see the histogram buckets. But every time the query fires, it aggregates the select result set to the existing buckets, causing a continuously increasing number in the bucket. For example: if there is 100 rows in the table. First run will fill the buckets with the 100 rows (_COUNTER = 100). Next run (20 sec later) the 100 record and the new records is aggregated again to the buckets and (_COUNTER = 200+) and so on.

Is there any way to aggregate only the new records, or reset the buckets every time when the query fires?

**Comment by albertodonato** [comment]
That's not how Histograms work in Prometheus (see https://prometheus.io/docs/practices/histograms/ for details)
Histograms track count of observations and totals, globally and per-bucket).

If you're looking for number of events over time, you might want to use a Counter and plot the variation over time (which basically gives you the number of events per time unit).

Histograms are useful when you're interested about number of observations per bucket.

**Comment by vargazs** [comment]
Thank you Alberto for the quick response. My explanation of the problem was not clear.

My query (SELECT event_length AS metric2 from event_length) returns all observations, not only the observations after the previous scrape. When Prometheus scrapes the exporter it retrieves all the observations and aggregates then to the buckets. If there is 100 observation in the table (not increasing), after 5 scrape the _total will count 500.

**Comment by albertodonato** [comment]
Thanks for clarifying the issue.
There's currently no way to reset a metric (which would be tricky since different queries can update the same metric, and it could lead to misreporting data).
Given your query is timed and runs every 20 seconds, what you could perhaps do is limit the query to only events from the last 20 seconds.
That way you only collect the new events. This of course assumes you have (or could add) a timestamp field in that table.

**Comment by vargazs** [comment]
Thank you for your response. That could be the solution!
