### ISSUE TITLE
Metrics for query time

### ISSUE THREAD

**Issue by richardmoe** [albertodonato/query-exporter#46]
**Is your feature request related to a problem? Please describe.**

Is it possible to get the execution time of a query as a metric?

**Describe the solution you'd like**
Have a config section for `timed_queries` where you could specify sql queries. This would return the time it took to execute the query.

**Describe alternatives you've considered**

**Additional context**

**Comment by albertodonato** [comment]
That's an interesting feature.
I think it could be added as a global metric, for all queries (like `queries` and `database_errors`), with a label for the query name and database.

I'll have a look to see whether it's possible to get the execution timing directly from SQLAlchemy, or needs to be manually timed.
