### ISSUE TITLE
Oracle not supported in docker image

### ISSUE THREAD

**Issue by xuanyuanaosheng** [albertodonato/query-exporter#47]
We use oracledb as datasource, But I have test the images: adonato/query-exporter:2.4.0.   It does not support the oracledb.

The error message: **module "cx_Oracle" not found**

The connection is as :

`databases:
  testdb:
    dsn: oracle+cx_oracle://_account_:_password_@(DESCRIPTION_LIST = (LOAD_BALANCE=OFF) (FAILOVER=ON) (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = _test01_)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = _servicename_))) (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = _test02_)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = _servicename_))))`

**Comment by albertodonato** [comment]
Hi,

the docker image doesn't support Oracle (the list of supported ones is [here](https://github.com/albertodonato/query-exporter#run-in-docker)).
The cx_Oracle module needs additional libs installed that need to be manually downloaded from Oracle  (see https://www.oracle.com/database/technologies/instant-client.html)

**Comment by xuanyuanaosheng** [comment]
@albertodonato  Ok. The new error is 


`2020-06-25 07:45:04,020 - ERROR - query-exporter - error from database "test1": (cx_Oracle.DatabaseError) DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help`

I will change the Dockerfile to support the oracle. Thanks for your help.

**Comment by andy812** [comment]
Just built an image:
```
FROM adonato/query-exporter:2.4.0
RUN pip install cx_Oracle && apt install libaio1 && mkdir -p /opt/oracle
COPY instantclient_19_8 /opt/oracle/instantclient_19_8/
ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_19_8
```
and it works with my Oracle DB.
`instantclient_19_8` is the folder from https://download.oracle.com/otn_software/linux/instantclient/19800/instantclient-basiclite-linux.x64-19.8.0.0.0dbru.zip

**Comment by albertodonato** [comment]
Hi @andy812,

thanks for sharing this. Do you happen to know what is the licensing for the oracle client?

**Comment by andy812** [comment]
@albertodonato https://www.oracle.com/database/technologies/faq-instant-client.html says:
Instant Client is free from OTN for anyone to use in a development or production environment. However, customers can only call Oracle Support if they already have a standard support contract.
More info about OTN here:
https://www.oracle.com/downloads/licenses/distribution-license.html

**Comment by albertodonato** [comment]
https://github.com/albertodonato/query-exporter/pull/60 should provide Oracle support in the docker image.

**Comment by xuanyuanaosheng** [comment]
@albertodonato  @andy812 Handsome!
