### ISSUE TITLE
Query-Exporter issue 

### ISSUE THREAD

**Issue by patilpravin557** [albertodonato/query-exporter#48]
Hi,

Have developed db2 query exporter for Prometheus,
build this select query,
select name as "db2_mycounter_name", total as "db2_mycounter_total" from myfakecounter

and inserted 2 values into table
insert into myfakecounter values ( 'counter1', 100 )
insert into myfakecounter values ( 'counter2,   200 )

I'm able to see both values in Prometheus console.

However, after a while, i have deleted counter2 value i.e 200 in this case from database.

But in Prometheus from query exporter select query i'm seeing 200 value still .
Its not showing me the existing results of select query i.e only counter 1 value

**Comment by albertodonato** [comment]
Can you share your configuration? How are metrics defined?

**Comment by patilpravin557** [comment]
apiVersion: v1
data:
  config.yaml: |-
    databases:
      db2:
        dsn: db2+ibm_db://xx:xx@xxxx:50000/<db name>
    metrics:
     db2_myfakecounter_total:
      type: gauge
      description: A sample gauge
      labels: [myfakecounter_name]
    queries:
       query1:
        interval: 5
        databases: [db2]
        metrics: [db2_myfakecounter_total]
        sql: select name as "myfakecounter_name", total as "db2_myfakecounter_total" from myfakecounter
kind: ConfigMap
metadata:
  name: db2exporter-config
 
---

**Comment by albertodonato** [comment]
Right, so that is expected behavior (see #26).
query-exporter accumulates metrics and exposes them to prometheus. what you see when querying `/metrics` is not just the current status, but the whole history (otherwise things like counters and histograms/summaries wouldn't work).

That's fine, because Prometheus takes care of figuring out differences between scrapes.

**Comment by patilpravin557** [comment]
so is there any way to handle it currently, 
are we planning to clean the steal metrics and which can handle by query exporter in upcoming patch/release

**Comment by albertodonato** [comment]
What I meant is that it's not a bug, it's the way prometheus client libraries work.

Is that causing issues in your setup?

**Comment by patilpravin557** [comment]
Actually not causing any issues on set up, but the actual problem is when i run the  application status query,

Let's say example,

Locked 20
running 10
and 5 sec  
running 30

Prometheus would see
Locked 20
Running 30

ideally is should be like 
Locked 0
and Running 30

However, its keep showing me Locked 20 for rest of the time...not showing me the current status value which is Locked 0

Hope you got my point?

**Comment by albertodonato** [comment]
I think the easiest way would be to set the value to 0 inthe db instead of deleting it. That way you always have one entry for each expected status.

**Comment by patilpravin557** [comment]
Ok  Many thanks....
wondering if any way this can be handle using Prometheus query language.
