### ISSUE TITLE
feature request: use env variables in config

### ISSUE THREAD

**Issue by toimtoimtoim** [albertodonato/query-exporter#5]
I would like to dockerise query-exporter for our test/prelive/live environments. Only difference between envs is connection url that I would like to expose/pass in docker image as environment variable

ala config.yml would be
```
databases:
  db1:
    dsn: ${CONNECTION_URL}
```
and then start
```
export CONNECTION_URL=oracle+cx_oracle://user:password@localhost:1521/XE 
query-exporter config.yml
```

I'm no python wizard but it seems doable https://stackoverflow.com/questions/52412297/how-to-replace-environment-variable-value-in-yaml-file-to-be-parsed-using-python

**Comment by albertodonato** [comment]
I'm a bit worried to allow using env vars anywhere in the config but it does make sense to allow it in the context of the database dsn, as per your example above.

Maybe something like this:

```
databases:
  db1:
    dsn: env:CONNECTION_URL
```

allowing to either specify the `dsn` in the config file, or get it from the environment.

**Comment by aldas** [comment]
well, I can see use cases when env replacement is handy in queries and labels - this is when you would like to have things like 'schema' name changeable or labels depending on the env name.

**Comment by albertodonato** [comment]
yeah perhaps it could be done for labels too. I don't like it for queries as it's subject to SQL injection

**Comment by aldas** [comment]
SQL injection - ff you are able to modify env variables then you have probably rights to modify conf also and do much more. And is it not that periodical query loop is separated from prometheus http endpoint part in code and conf/yaml parsing and env replacement is done only in service startup.

anyway, ability to use env variables in connection url and labels is good enough for starters.

**Comment by albertodonato** [comment]
Actually, I just realized you can't have additional labels in metrics, as the exporter has no way of deciding values for those. The only one that's added is `database`.

So what I proposed at the beginning should be enough.

**Comment by toimtoimtoim** [comment]
@albertodonato do you know then version 1.7.0 will be available from pip3? Currently if I install on Centos7 I get 1.6.0

```
[user@prom ~]$ pip3 list
Package                Version
---------------------- -------
...
query-exporter         1.6.0 
...
```

**Comment by albertodonato** [comment]
@toimtoimtoim oops, forgot to upload the release. It should be good now.

**Comment by GBuchanon** [comment]
I have a database name with a dash in it.  I have to override the database label as such because the YAML cant have a dash in the db name.  Even better would be to pass in the db name as an environment variable as the environment variable can be passed in by build system.

```
databases:
  exampledbname:
    dsn: env:CONNECTION_STRING
    autocommit: false
    labels:
      database: Example-DB-Name
```

This would be great

```
databases:
  exampledbname:
    dsn: env:CONNECTION_STRING
    autocommit: false
    labels:
      database: ${DATABASE_NAME}     or even env:DATABASE_NAME
```
