### ISSUE TITLE
Log query execution timings

### ISSUE THREAD

**Issue by lenalebt** [albertodonato/query-exporter#52]
**Is your feature request related to a problem? Please describe.**
Maybe I have overlooked a configuration, but I could not find this in the Readme.

We use the query-exporter with different kinds of queries: some are short-running, and run quite often - others are rarely running, and can run for quite long (minutes, 10s of minutes). While I too think that those long-running queries are problematic, we cannot easily get rid of them.

Especially while setting them up initially, it's hard to see though when the queries run, and whether they should already have returned with data or not. Making it possible to activate logging (for start & end of a query) would really help when debugging queries.

**Describe the solution you'd like**
I'd love to either have a general configuration to switch on query logging for all queries, or to do it on a per-query-basis. Having the possibility for all queries would already help a lot - we could turn it on when needed, and turn it off normally.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by albertodonato** [comment]
Have you tried enabling debug log with `-L DEBUG`? That will log every time a query is run and which metrics are updated as result of queries.

I'm not sure if that covers your case, but it might be a start. If not, I'd be nice to know what's missing.

**Comment by lenalebt** [comment]
Hi!
I was so unused to setting this stuff via commandline options that I simply did not check for it, expected it in the config files. Sorry to bother you! I created a short pull request for others that run into the same trap.

One thing that imho is missing is a log line when the query completes (together with a timing). That would help for cases of those long-running queries.

**Comment by albertodonato** [comment]
I'm closing this since query latencies are now reported as a butilin `query_latency` metric
