### ISSUE TITLE
Add support for setting a timeout for queries

### ISSUE THREAD

**Issue by invokermain** [albertodonato/query-exporter#54]
Cool project, I have been using another SQL exporter but they are not actively maintained, so I am keen to switch to this project instead (also Python is nice).

Quick question as this is crucial for us to use this exporter in production.  Is it possible to set query timeouts on a global or per query basis? I can't find anything while reading (skimming) over the docs.

**Comment by albertodonato** [comment]
Hi, it's not currently possible to set it in the exporter configuration (shouldn't be too hard to do that though and it makes sense as a feature).

You might be able to do that globally (per-database) via the `connect-sql` option, depending on whether your database supports it (e.g. in PostgreSQL you could use `SET statement_timeout TO xxx`).

I'll mark this as an enhancement as it makes sense to have it configurable per-query.

**Comment by invokermain** [comment]
Cool thanks! I think MS SQL does not have great support for timeouts, which means it has to be done client side unfortunately.

Could potentially have a 'query_time_out' built-in metric to allow easy visibility and alerting off the back of that. 'query_latency' is already a great feature by the way.

**Comment by albertodonato** [comment]
Right, having a per-query timeout would be interesting to have, and the builtin `queries` metric could grow a new status value for `timeout` (in addition to `success` and `failure`).

I'll definitely have a look at adding that as soon as I can
