### ISSUE TITLE
Error while running SQL queries

### ISSUE THREAD

**Issue by vaibhav021099** [albertodonato/query-exporter#55]
I tried connecting the query exporter to MySQL and OracleDB. 
In both the cases I'm getting the following error - 
ERROR - query-exporter - query "count" on database "demo" failed: Wrong column names from query.
I'm new to prometheus and am unaware of the fact that why I'm getting this error.
Please help!

**Comment by albertodonato** [comment]
Can you share your config?
The error means your query is returning columns whose name doesn't match the expected ones for metrics/labels.

**Comment by vaibhav021099** [comment]
databases:
  demo:
    dsn: 'mysql://root:V@ibhav02@127.0.0.1:3306/database'

metrics:
  metric1:
    type: counter
    description: A sample counter

queries:
  query1:
    databases: [demo]
    metrics: [metric1]
    sql: |
      SELECT CPU FROM database.data WHERE IDLE=23;

**Comment by vaibhav021099** [comment]
databases:
  demo:
    dsn: 'mysql://root:V@ibhav02@127.0.0.1:3306/demo'

metrics:
  metric1:
    type: counter
    description: A sample counter

queries:
  query1:
    databases: [demo]
    metrics: [metric1]
    sql: |
      SELECT Count FROM demo.billing WHERE CAT = 'Success' AND Region = 'US'

**Comment by vaibhav021099** [comment]
databases:
  demo:
    dsn: 'mysql://root:V@ibhav02@127.0.0.1:3306/demo'

metrics:
  metric1:
    type: gauge
    description: A sample counter

queries:
  query1:
    databases: [demo]
    metrics: [metric1]
    sql: |
      SELECT Count FROM demo.billing WHERE CAT = 'Success' AND Region = 'US'

**Comment by vaibhav021099** [comment]
I was making a very silly mistake. Figured it out from your reply!
Thanks.

**Comment by anurag-appperfect** [comment]
Hey, I am facing the similar issue while running the query-exporter can anybody please help
