### ISSUE TITLE
For the label can't supporter Chinese char

### ISSUE THREAD

**Issue by searchgithub** [albertodonato/query-exporter#59]
**Is your feature request related to a problem? Please describe.**
When I get the value from DB that column has Chinese char, it will show "??"

**Describe the solution you'd like**
Remove the Chinese columns, hope it can support

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by albertodonato** [comment]
Label names (as metric names) only support ASCII alphanumeric chars (see https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels).
This is not an exporter limitation, it's a Prometheus rule.

To make it work, you'll have to use a different label name and use aliasing in your query to rename the column (e.g. `SELECT <your_column_name> AS <label_name>`.

**Comment by searchgithub** [comment]
Thanks a lot for your explaination.

**Comment by searchgithub** [comment]
what about the lable_value?

**Comment by albertodonato** [comment]
Values can be unicode strings, so it should work fine if those are utf-8 encoded.
