### ISSUE TITLE
MSSQL Queries not working

### ISSUE THREAD

**Issue by jehlert** [albertodonato/query-exporter#61]
Queries are not working against a MSSQL database. Depending on the driver, there is either an error when using pyodbc - `sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY010', '[HY010] [unixODBC][Driver Manager]Function sequence error (0) (SQLFetch)')` or no results returned when using pymssql. I'm running the latest docker image.

**Installation details**

- operating system: [OS and version]
- query-exporter installation type:
  - pip:
```
Package                Version Location                                                
---------------------- ------- --------------------------------------------------------
adodbapi               2.6.2.0 
aiohttp                4.0.0a1 
argcomplete            1.12.0  
async-timeout          3.0.1   
attrs                  20.1.0  
chardet                3.0.4   
croniter               0.3.34  
cx-Oracle              8.0.1   
Cython                 0.29.21 
ibm-db                 3.0.2   
ibm-db-sa              0.3.5   
idna                   2.10    
importlib-metadata     1.7.0   
jsonschema             3.2.0   
multidict              4.7.6   
natsort                7.0.1   
outcome                1.0.1   
pip                    19.0.3  
prometheus-aioexporter 1.6.2   
prometheus-client      0.8.0   
pyodbc                 4.0.30  
pyrsistent             0.16.0  
python-dateutil        2.8.1   
PyYAML                 5.3.1   
query-exporter         2.4.0  
Represent              1.6.0   
setuptools             40.8.0  
six                    1.15.0  
SQLAlchemy             1.3.19  
sqlalchemy-aio         0.16.0  
toolrack               3.0.0   
typing-extensions      3.7.4.3 
yarl                   1.5.1   
zipp                   3.1.0 
```
  - docker image: lastest
  - snap: N/A

**To Reproduce**

If possible, please provide detailed steps to reproduce the behavior:

1. Config file content (redacted of secrets if needed)
Below is a sample, I've simplified the query to `select 1` and modified the config to reflect that, but still get the same error. 
```
databases:
  sqlserver:
    dsn: mssql+pyodbc://un:pw@hostname:1433/dbname?driver=ODBC+Driver+17+for+SQL+Server
metrics:
  etl_job_running:
    type: gauge
    description: Represents whether an ETL job is running
    labels: [error_code, procedure_name, database_name]
queries:
  etl_job_running_stats:
    interval: 5
    timeout: 15
    databases: [sqlserver]
    metrics: 
      - etl_job_running
    sql: |
      select DBName                                                       as database_name,
  		 ProcName                                                     as procedure_name,
  		 case when ActionDesc like 'PROCESS START%' then 1 else 0 end as etl_job_running,
  		 ErrorCd                                                      as error_code
  		from (
  		         select *,
  		                ROW_NUMBER() over (partition by DBName, ProcName order by CreateDt desc) as row_num
  		         from GD_Log.cal.uvw_Action_Log
  		         where ActionTypeCd = 'ETL'
  		     ) as partitioned_result
  		where row_num = 1
```

The best I can tell, the error is happening within the sqlalchemy_aio library. I wrote a quick python script to connect to the DB using pyodbc driver and ran the query above. I ran this inside the running docker image (latest tag) and verified that it was able to connect and fetch results from the DB.

**Comment by albertodonato** [comment]
Not sure if it's related, but could yu try adding `MARS_Connection=yes` to the DSN, as described in https://github.com/albertodonato/query-exporter/issues/57#issuecomment-660872872 and see if it helps?

**Comment by jehlert** [comment]
@albertodonato MARS_Connection didn't work. However, specifying `autocommit: false` fixes it. Have you seen this before?

**Comment by albertodonato** [comment]
Not for mssql specifically, but there have been reports where either enabling or disabling autocommit fixes issues.
That's why I ended up adding a parameter to disable it.

Good to know that it fixed your case. I'll mark the bug closed. Feel free to reopen if something new comes up.
