### ISSUE TITLE
query exporter alert

### ISSUE THREAD

**Issue by xuanyuanaosheng** [albertodonato/query-exporter#63]
The query-exporter is a great tool for prometheus monitor.

The new feature:

I want to send the query results to the alert manager directly through query-exporter. 

- The **description** is a field in database.
- The other field is a label.

https://github.com/prometheus/alertmanager/blob/master/examples/ha/send_alerts.sh

**Comment by albertodonato** [comment]
It feels a bit weird to be duplicating something that Prometheus already provides.

Exporters are meant to provide data to Prometheus, which in turn can send alerts to alertmanager.
Why would you need to be sending alerts directly and not via Prometheus?

**Comment by xuanyuanaosheng** [comment]
@albertodonato  This is a common tools for query database alert, I can not find a good way to do this. 
I don't need to add the query result to prometheus.  The alert description is as a field in the databases, the prometheus alert description is fixed.

**Comment by invokermain** [comment]
just export to Prometheus & have your alert query as `sql_alerts` or whatever you call the metric and it will fire to your alert manager?

**Comment by xuanyuanaosheng** [comment]
@invokermain  I have considered your proposal. However, our actual use scenario is that Prometheus is not installed.  We only have      
database installed.

**Comment by invokermain** [comment]
@xuanyuanaosheng that doesn't make sense, you can't miss out a key piece of the puzzle and expect to work. Running a Prometheus instance is free and super easy, and will definitely be a lot easier than anything else you will have to try to get it to work.

**Comment by albertodonato** [comment]
Closing this as the feature doesn't really fit the project.

As discussed above, prometheus + altermanager should be used in that case
