### ISSUE TITLE
Chinese labels from database not displayed correctly

### ISSUE THREAD

**Issue by PaulYuanJ** [albertodonato/query-exporter#65]
**Describe the bug**
when I use query-exporter and query data from oracle and Chinese as the value of label, the Chinese will display as below: 
`resultcount{resultname="????,???????????????????????"} 104.0
`

**To Reproduce**

I have create a script by using sqlalchemy, it could display Chinese normally:

```
from prometheus_client import start_http_server, Gauge
import sqlalchemy as sql

def get_data_from_db():
    connect_string = "........."
    sql_engine = sql.create_engine(connect_string)
    sql_string = "......."
    conn = sql_engine.connect()
    result = conn.execute(sql_string)
    label_value = result.first()
    return label_value

if __name__ == '__main__':
    label_value = get_data_from_db()
    aaa = Gauge('test_metrics', 'test test_metrics', ['first_lable'])
    aaa.labels(label_value).set(10)
    start_http_server(10000)
    while True:
        pass
```

here's the prometheus metrics:

\# HELP test_metrics test test_metrics
\# TYPE test_metrics gauge
test_metrics{first_lable="空号"} 10.0

Would you like to help me if it could display Chinese and how to make it to display Chinese normally?

**Comment by albertodonato** [comment]
Hi, could you please add details about what your query-exporter configuration is, and possibly some examples of values from the db and what you're actually getting in labels?

**Comment by PaulYuanJ** [comment]
> Hi, could you please add details about what your query-exporter configuration is, and possibly some examples of values from the db and what you're actually getting in labels?

Sorry for delay, I just edit my description in the comment.

**Comment by PaulYuanJ** [comment]
It will be very perfect if the README could descript how to run this project in pycharm.

I have cloned this project, but it is hard for me to run it to do debug about the "character encoding issue".

**Comment by albertodonato** [comment]
If you create a virtualenv for the project, you can run `query-exporter` once you activate the virtualenv.

**Comment by PaulYuanJ** [comment]
> If you create a virtualenv for the project, you can run `query-exporter` once you activate the virtualenv.

Thank you very much for your quick response, It is really very nice of you. 

I tried, but failed, perhaps there's something wrong with my env.


(venv) D:\PycharmProjects\query-exporter>query-exporter
'query-exporter' is not recognized as an internal or external command,
operable program or batch file.

**Comment by xuanyuanaosheng** [comment]
@albertodonato
 
I have using the docker images to query mysql database.

- mysql version: 8.0.20, the charset: utf8mb4
+--------+--------+---------+
| name1  | name2  | metric2 |
+--------+--------+---------+
| 中国      |  美国   |       2      |
| 中国      | 日本    |       1      |
| 日本      | 美国    |       1      |
| a            | b         |       1     |
+--------+--------+---------+
  
- query-exporter image: latest

---------------------------
The sql:  SELECT c1 as name1 ,c2 name2, count(1) as metric2 from t3 group by c1 ,c2 ;

The result:

metric2{app="app1",database="db1",name1="??",name2="??"} 2.0
metric2{app="app1",database="db1",name1="a",name2="b"} 1.0

Can you help locate the problem? Is it a program problem or a docker images problem?

**Comment by albertodonato** [comment]
Thanks for providing a sample of the database content.
It seems the issue might be with encoding (utf8 vs utf8mb4).
I'll take a look at the issue as soon as I can.

**Comment by xuanyuanaosheng** [comment]
@albertodonato  I also test using sql_exporter： https://github.com/free/sql_exporter. The result looks good.  Please help to test the query-exporter.

**Comment by albertodonato** [comment]
One quick test you could do is to add `?charset=utf8mb4` to the DSN string.
That might workaround the issue

**Comment by xuanyuanaosheng** [comment]
@albertodonato  when add `?charset=utf8mb4` , It (mysql) works fine. 
---
I solved the problem, when query the oracledb must add  ` -e NLS_LANG=AMERICAN_AMERICA.UTF8 `. 

This issue can be closed.

Thanks.

**Comment by albertodonato** [comment]
Thank you for testing it.

I'll leave the issue open for now as I think it could also make sense to allow passing the encoding for the database (so you don't have to pass the charset in the dsn).

I'll add an option for it.

**Comment by albertodonato** [comment]
I tried with a simple mysql database using `utf8mb4` encoding:

```
mysql> select * from test;
+--------+--------+-------+
| name1  | name2  | value |
+--------+--------+-------+
| 中国   | 美国   |     2 |
| 中国   | 日本   |     1 |
| foo    | bar    |     3 |
+--------+--------+-------+
3 rows in set (0.00 sec)
```

The exporter works fine for me even without adding the charset option:

```
value{database="mysql",name1="中国",name2="美国"} 2.0
value{database="mysql",name1="中国",name2="日本"} 1.0
value{database="mysql",name1="foo",name2="bar"} 3.0
```

**Comment by albertodonato** [comment]
Nevermind, I managed to reproduce the issue with the docker image

**Comment by albertodonato** [comment]
After testing and looking around for more info, it seems indeed that the right way is to pass the charset in the dsn (IOW `?charset=utf8mb4`).

Marking this as closed as it's not really an exporter issue.
