### ISSUE TITLE
windows installation

### ISSUE THREAD

**Issue by GhasemSystem** [albertodonato/query-exporter#74]
Hi
How can I install this tools on windows server?
Should I use Docker?

**Comment by albertodonato** [comment]
I'm not familiar with Windows Server. nor Docker on Windows.

query-exporter itself is pure python, so you should be able to run it even directly on windows, provided that all dependencies are available.

**Comment by GhasemSystem** [comment]
thank you @albertodonato 
I will install docker via WSL on windows and after that use from it for setup this nice tool :)

**Comment by GhasemSystem** [comment]
Can you suggest me for find a link for installing python3 on windows?
