### ISSUE TITLE
[Snap] Unable to disable SSL/go around SSL error with mysql

### ISSUE THREAD

**Issue by ibexa-yuna** [albertodonato/query-exporter#75]
**Describe the bug**

I'm using AWS RDS to run MySQL 5.6.44 and query-exporter fails to connect to MySQL server due to SSL error.
```
2020-12-23T09:33:14Z query-exporter.daemon[801417]: 2020-12-23 09:33:14,150 - ERROR - query-exporter - error from database "monitorDB": (MySQLdb._exceptions.OperationalError) (2026, 'SSL connection error: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol')
2020-12-23T09:33:14Z query-exporter.daemon[801417]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Installation details**

- operating system: CentOS 8
- openssl version: `OpenSSL 1.1.1c FIPS  28 May 2019`
- query-exporter installation type:
  - snap:
```
name:      query-exporter
summary:   Export Prometheus metrics from SQL queries
publisher: Alberto Donato (ack)
store-url: https://snapcraft.io/query-exporter
contact:   https://github.com/albertodonato/query-exporter/issues
license:   GPL-3.0+
description: |
  query-exporter is a Prometheus exporter which allows collecting metrics from
  database queries, at specified time intervals or when a request to the
  metrics endpoint is performed.
  
  Each query can be run on multiple databases, and update multiple metrics.
  
  The snap provides both the `query-exporter` command and a deamon instance of
  the command, managed via a Systemd service.
  To run the latter:
  
    - create or edit `/var/snap/query-exporter/current/config.yaml` with the
      configuration
    - run `sudo snap restart query-exporter`
  
  Currently supported databases are:
  
    - PostgreSQL (`postgresql://`)
    - MySQL (`mysql://`)
    - SQLite (`sqlite://`)
    - Microsoft SQL Server (`mssql://`)
    - IBM DB2 (`db2://`) on supported architectures (x86_64, ppc64le and
      s390x)
commands:
  - query-exporter
services:
  query-exporter.daemon: simple, enabled, active
snap-id:      ssukadvQVTCbvJ0h7QH6ouseq7X9vbib
tracking:     latest/stable
refresh-date: 3 days ago, at 17:34 UTC
channels:
  latest/stable:    2.6.1 2020-12-20 (717) 50MB -
  latest/candidate: ↑                           
  latest/beta:      ↑                           
  latest/edge:      2.6.1 2020-12-20 (717) 50MB -
installed:          2.6.1            (717) 50MB -
```

**To Reproduce**

I have defined connection string as follows:
```
databases:
  monitorDB:
    dsn: mysql://username:password@hostname:3306/DATABASE
    keep-connected: false
    labels:
      region: eu-west-1
```

Query Exporter was working fine beforehand but then started having connection issues like these.
No upgrades were performed on the AWS RDS side, except patch version upgrades, as well as no configuration changes related to SSL were done.

**Comment by albertodonato** [comment]
Looking at this post https://stackoverflow.com/questions/53058362/openssl-v1-1-1-ssl-choose-client-version-unsupported-protocol, this might be related to a mismatch in enabled/supported TLS versions.

Up until 2.4.0, the snap was using a 18.04 base, it's now based on 20.04, so it uses a newer openssl.
I'm not sure if you can change the client-side defaults (e.g. via env vars), but this likely means the server side is using a weak cypher.

**Comment by ibexa-yuna** [comment]
I guess I just need to upgrade RDS to 5.6.46 and later...
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.SSLSupport

I will try and revert back.

**Comment by albertodonato** [comment]
Closing the issue as it doesn't seem to be an issue with query-exporter
