### ISSUE TITLE
sqlite - connection error

### ISSUE THREAD

**Issue by szubair** [albertodonato/query-exporter#77]
Hi - I'm getting below error messages when I try to connect sqlite3 database using query-exporter. I have given 777 file permission to the dbfile. 

The config file:
----------------
databases:
  db1:
    dsn: sqlite:///usr/local/bin/ncncncn/logs/system_logs.idb
    keep-connected: false
 
---cut---
2021-01-29T18:29:18Z query-exporter.daemon[2415884]: 2021-01-29 11:29:18,448 - ERROR - query-exporter - error from database "db1": (sqlite3.OperationalError) unable to open database file
2021-01-29T18:29:18Z query-exporter.daemon[2415884]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
---cut---

**Installation details**
- operating system: [Linux - RHEL 8.3]
- Installed using snap
query-exporter  2.6.1     717    latest/stable  ack

**Comment by albertodonato** [comment]
The snap is fully confined, so it won't be able to read files from the system, outside of the home directory of the user that's running it.

If you're using the daemon instance inside the snap, it will run as root, thus it will only be able to read files under `/root`.

**Comment by szubair** [comment]
Hi Alberto,
I tried copying system_logs.idb in many places like /tmp/mydir, /var/snap/query-exporter/common and still I got the same error.
""ERROR - query-exporter - error from database "db1": (sqlite3.OperationalError) unable to open database file""
Could you please suggest where should I keep the sqlite3 datafile ? Thanks

**Comment by albertodonato** [comment]
Putting the file under `/var/snap/query-exporter/common` should work, assuming the file is owned by root. Also, putting it under `/root` should be fine.

Note that the URI syntax for sqlite when using a file is `sqlite:////var/snap/query-exporter/common/db.sqlite` (with four slashes).

**Comment by szubair** [comment]
> Putting the file under `/var/snap/query-exporter/common` should work, assuming the file is owned by root. Also, putting it under `/root` should be fine.
> 
> Note that the URI syntax for sqlite when using a file is `sqlite:////var/snap/query-exporter/common/db.sqlite` (with four slashes).

I really appreciate your prompt response.
URI syntax hint (four slashes) saved me .. thanks.
