### ISSUE TITLE
MARS_Connection NOT work

### ISSUE THREAD

**Issue by GhasemSystem** [albertodonato/query-exporter#78]
"MARS_Connection" not work when use key/value format in dsn whereas this key is work when use it in simple connection string mode

**Comment by albertodonato** [comment]
Can you please include your `databases` config section?

**Comment by GhasemSystem** [comment]
WORK:
   mssql+pyodbc://x:x@test\sql14/mydb?MARS_Connection=yes&driver=ODBC+Driver+17+for+SQL+Server
NOT WORK:
    dsn:
      dialect: mssql+pyodbc
      user: x
      password: x
      host: test\sql14
      database: mydb
      options:
        driver: ODBC Driver 17 for SQL Server
        MARS_Connection: yes
    keep-connected: true
    autocommit: false

**Comment by albertodonato** [comment]
can you try with `MARS_Connection: "yes"`?

**Comment by GhasemSystem** [comment]
no!
I test it and notify here

**Comment by GhasemSystem** [comment]
with this trick : MARS_Connection: "yes" my problem is solved
thanks
