### ISSUE TITLE
mssql in docker mod not work!

### ISSUE THREAD

**Issue by GhasemSystem** [albertodonato/query-exporter#80]
my config in docker mode for sqlserver not work

my dsn config is:
    mssql+pyodbc://x:x@test\sql14/mydb?MARS_Connection=yes&driver=ODBC+Driver+17+for+SQL+Server

Error: 
    No driver name specified; this is expected by PyODBC when using DSN-less connections

**Comment by albertodonato** [comment]
It seems you're using special chars in your password. As described in https://docs.sqlalchemy.org/en/14/core/engines.html#database-urls you need to URL-encode the password.

Alternatively you can use the split `dsn` configuration (see https://github.com/albertodonato/query-exporter#databases-section) which automatically encodes user/password.

That might be the cause of the error you're seeing.

**Comment by GhasemSystem** [comment]
thanks
so ODBC Driver 17 is installed builtin on container?

**Comment by albertodonato** [comment]
yes, it's included in the docker image (see also https://github.com/albertodonato/query-exporter/issues/42)
