### ISSUE TITLE
Issue with % characters in SQL query

### ISSUE THREAD

**Issue by rolanddb** [albertodonato/query-exporter#84]
**Describe the bug**

I'm trying to run a query with `%` characters and get an error about parameters.

**Installation details**

- query-exporter installation type:
  - docker image: 2.6.2 and 2.7.0

**To Reproduce**
I'm running the following query against MS Sql server:
```
SELECT

      rp.[name] AS resource_pool,

      ISNULL(rps.[Sessions], 0) AS sqlservermi_resourcepool_sessions,

      ISNULL(rps.[Requests], 0) AS sqlservermi_resourcepool_requests,

      ISNULL(rps.TotalCurrentWaitTime, 0) AS sqlservermi_resourcepool_current_wait_time_seconds,

      pc24.cntr_value * 1024 AS sqlservermi_resourcepool_max_memory_bytes,

      pc30.cntr_value * 1024 AS sqlservermi_resourcepool_used_memory_bytes,

      pc14.cntr_value / pc15.cntr_value AS sqlservermi_resourcepool_cpu_usage_ratio,

      ISNULL(rps.BlockedSessions, 0) AS sqlservermi_resourcepool_blocked_sessions,

      ISNULL(rps.BlockedSessionsBySelf, 0) AS sqlservermi_resourcepool_blocked_sessions_by_self

      FROM sys.resource_governor_resource_pools AS rp

        LEFT OUTER JOIN (

          SELECT

            wg.pool_id,

            COUNT(1) AS [Sessions],

            SUM(CASE WHEN er.request_id IS NULL THEN 0 ELSE 1 END) AS [Requests],

            SUM(CAST(er.wait_time AS BIGINT)) AS TotalCurrentWaitTime,

            SUM(CASE WHEN er.blocking_session_id <> 0 THEN 1 ELSE 0 END) AS BlockedSessions,

            SUM(CASE WHEN er.blocking_session_id <> 0 AND er.blocking_session_id = er.session_id THEN 1 ELSE 0 END) AS BlockedSessionsBySelf

          FROM sys.dm_exec_sessions AS ses

            INNER JOIN sys.resource_governor_workload_groups AS wg ON (wg.group_id = ses.group_id)

            LEFT OUTER JOIN sys.dm_exec_requests AS er ON (er.session_id = ses.session_id)

          GROUP BY wg.pool_id) AS rps ON (rps.pool_id = rp.pool_id)

        LEFT OUTER JOIN sys.dm_os_performance_counters AS pc14 ON (pc14.instance_name = rp.[name] AND pc14.counter_name = 'CPU usage %' AND pc14.[object_name] LIKE '%:Resource Pool Stats%')

        LEFT OUTER JOIN sys.dm_os_performance_counters AS pc15 ON (pc15.instance_name = rp.[name] AND pc15.counter_name = 'CPU usage % base' AND pc15.[object_name] LIKE '%:Resource Pool Stats%')

        LEFT OUTER JOIN sys.dm_os_performance_counters AS pc24 ON (pc24.instance_name = rp.[name] AND pc24.counter_name = 'Max memory (KB)' AND pc24.[object_name] LIKE '%:Resource Pool Stats%')

        LEFT OUTER JOIN sys.dm_os_performance_counters AS pc30 ON (pc30.instance_name = rp.[name] AND pc30.counter_name = 'Used memory (KB)' AND pc30.[object_name] LIKE '%:Resource Pool Stats%')           

        

      ;
```
The query yields 1 label column and 8 metric columns.

However this gives an error `Parameters for query "resourcepool_query" don't match those from SQL`. 

We do not use parameters for this query (nor anywhere else in the config.yml). 

When I eliminate the `%` characters then everything is fine, so the config.yml has the correct syntax and the problem is in the query. I have found this issue #21 which states that escaping should no longer be necessary. I have tried escaping by replacing `%` with `%%` and `\%` but the issue remains. Do you have any idea how to resolve this?

Note that the first `%` after `CPU usage` should be a literal and the second are part of the LIKE clause.

**Comment by albertodonato** [comment]
query-exporter uses the "named" paramstyle for queries.

I think what's tripping up your SQL is actually the semicolons (e.g. `LIKE '%:Resource Pool Stats%'`) because it matches `:Resource` as a parameter name.
Can you try escaping those (e.g. `\:Resource`)?

**Comment by rolanddb** [comment]
Hi @albertodonato, you're totally right. I removed the `:` and everything works fine. I totally missed that that character was in the query.

Thanks for the help and the great project!
