### ISSUE TITLE
Passwords are in clear text

### ISSUE THREAD

**Issue by mcarol44** [albertodonato/query-exporter#85]
**Is your feature request related to a problem? Please describe.**
In the query.yaml the username and passwords are in plain text. we need a way to hide those credentials if this has not already been solutioned. 
**Describe the solution you'd like**
We need a way to lock down the username and passwords or hide those in the file. 
**Describe alternatives you've considered**
I was thinking about putting the credentials in a different file and pulling them is a variables but that still leaves the credentials in plain text 
**Additional context**

**Comment by mcarol44** [comment]
Has anyone gotten this resolved. Is there a way to take the passwords out of the config file. Please let me know.

**Comment by albertodonato** [comment]
Currently you can specify to get the connection string from the environment via e.g. `dsn: env:CONNECTION_STRING` , and setting `$CONNECTION_STRING`. Depending on how you run the exporter, you can get that into the env without having in written in a file
