### ISSUE TITLE
docker not working in apple m1?

### ISSUE THREAD

**Issue by pablogrisafi1975** [albertodonato/query-exporter#93]
**Describe the bug**

I start the docker and server seems to hang. There is a warning

**Installation details**

- operating system: macOS BigSur 11.5.2 (20G95) on Apple M1
- query-exporter installation type:
   - docker image: latest
 
**To Reproduce**

If possible, please provide detailed steps to reproduce the behavior:

1. Config file content (redacted of secrets if needed)

       databases:
         db2:
           dsn: db2+ibm_db://uuuuuu:ppppp@db:port/bludb&security=SSL
           keep-connected: false
           labels:
             region: us2
             app: app1
              
       metrics:
         metric1:
           type: histogram
           description: A sample histogram
           labels: [ccc, prod]
              
       queries:
         query1:
           interval: 5
           databases: [db2]
           metrics: [metric1]
           sql: SELECT count(*) FROM CCC.FT_COGNITIVO AS metric1

2. Ran query-exporter with the following command line ...

       docker run -p 9560:9560/tcp -v "/Users/pablo.grisafi@ibm.com/soft/query-exporter/config.yaml:/config.yaml" --rm -it adonato/query-exporter:latest -L DEBUG

3. Output is

     WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
     2021-08-30 15:56:46,844 - INFO - aiohttp.web - Listening on http://0.0.0.0:9560
     2021-08-30 15:56:46,878 - INFO - query-exporter - version 2.7.0 starting up

and hangs, no metrics

**Comment by albertodonato** [comment]
The official image is only available for amd64 arch. You should be able to build it for arm64 too

**Comment by imavo** [comment]
This is the same symptom that I reported (on ubuntu 20.04 x64, without docker)  in ticket  https://github.com/albertodonato/query-exporter/issues/96  , also using Db2-LUW without ssl. Same symptom with the dsn string db2+ibm_db://   or  ibm_db_sa:// .   Need to be able to see what's happening under the cover, I get no no additional output even with the -L DEBUG command-line option.
