### ISSUE TITLE
How to build query-exporter?

### ISSUE THREAD

**Issue by NicoForce** [albertodonato/query-exporter#97]
This might be a noob question, I haven't found in the docs how to build the project, and am not too familiar with python projects, what steps can I follow to get the latest query_exporter from master?

**Comment by albertodonato** [comment]
As with most python projects, you can clone the repo and install in a virtualenv in a directory `$dir` with

```bash
python3 -m venv $dir
. ./$dir/bin/activate
pip install -e .  # from the project clone
```

The executable will be available under `$dir/bin/query-exporter`.

**Comment by NicoForce** [comment]
Thanks!
